export const API_ENDPOINTS = Object.freeze({
  HEALTH: "/health",
  HEALTH_STATUS: "/health/status",

  AUTH_STATUS: "/auth/status",
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
  LOGOUT: "/auth/logout",
  REFRESH_TOKEN: "/auth/refresh-token",
  ME: "/auth/me",
  FORGOT_PASSWORD: "/auth/forgot-password",
  RESET_PASSWORD: "/auth/reset-password",
  VERIFY_EMAIL: "/auth/verify-email",
  RESEND_VERIFICATION: "/auth/resend-verification",
  CHANGE_PASSWORD: "/auth/change-password",

  USERS_STATUS: "/users/status",
  PROFILE: "/profile",
  PROFILE_ABOUT: "/profile/about",
  PROFILE_ANALYTICS: "/profile/me/analytics",
  PROFILE_AVATAR: "/profile/avatar",
  PROFILE_COVER: "/profile/cover",
  PROFILE_EDUCATION: "/profile/education",
  PROFILE_EDUCATION_ITEM: (educationId) => `/profile/education/${encodeURIComponent(educationId)}`,
  PROFILE_EXPERIENCE: "/profile/experience",
  PROFILE_EXPERIENCE_ITEM: (experienceId) => `/profile/experience/${encodeURIComponent(experienceId)}`,
  PROFILE_UPLOAD_AVATAR: "/profile/upload-avatar",
  PROFILE_UPLOAD_COVER: "/profile/upload-cover",
  PROFILE_INTRO: "/profile/intro",
  PROFILE_ME: "/profile/me",
  PROFILE_OPEN_TO: "/profile/open-to",
  PROFILE_PRIVACY: "/profile/privacy",
  PROFILE_SERVICES: "/profile/services",
  PROFILE_SERVICE_ITEM: (serviceId) => `/profile/services/${encodeURIComponent(serviceId)}`,
  PROFILE_SKILLS: "/profile/skills",
  PROFILE_UPDATE_ME: "/profile/me",
  PROFILE_PUBLIC_BY_USERNAME: (username) => `/profile/${encodeURIComponent(username)}`,
  PROFILE_PUBLIC_ACTIVITY: (username) => `/profile/${encodeURIComponent(username)}/activity`,
  PROFILE_VERIFICATION: "/profile/verification",
  PROFILE_VERIFICATION_REQUEST: "/profile/verification/request",

  CONNECTION_STATUS: (userId) => `/connections/status/${encodeURIComponent(userId)}`,
  CONNECTION_REQUEST: (userId) => `/connections/request/${encodeURIComponent(userId)}`,
  CONNECTION_WITH_USER: (userId) => `/connections/user/${encodeURIComponent(userId)}`,

  FOLLOW_STATUS: (userId) => `/follows/status/${encodeURIComponent(userId)}`,
  FOLLOW_USER: (userId) => `/follows/${encodeURIComponent(userId)}`,

  CHALLENGES: Object.freeze({
    ARCHIVE: (id) => `/challenges/${encodeURIComponent(id)}/archive`,
    BASE: "/challenges",
    CLOSE: (id) => `/challenges/${encodeURIComponent(id)}/close`,
    DETAIL_BY_ID: (id) => `/challenges/id/${encodeURIComponent(id)}`,
    DETAIL_BY_SLUG: (username, slug) =>
      `/challenges/${encodeURIComponent(username)}/${encodeURIComponent(slug)}`,
    MY: "/challenges/me",
    PAUSE: (id) => `/challenges/${encodeURIComponent(id)}/pause`,
    PUBLISH: (id) => `/challenges/${encodeURIComponent(id)}/publish`,
  }),
  EXECUTION_PLANS: Object.freeze({
    ACCEPT: (id) => `/execution-plans/${encodeURIComponent(id)}/accept`,
    BASE: "/execution-plans",
    BY_CHALLENGE: (challengeId) =>
      `/execution-plans/challenge/${encodeURIComponent(challengeId)}`,
    CLIENT_DETAIL: (id) => `/execution-plans/client/${encodeURIComponent(id)}`,
    DETAIL_BY_ID: (id) => `/execution-plans/id/${encodeURIComponent(id)}`,
    MY: "/execution-plans/me",
    REJECT: (id) => `/execution-plans/${encodeURIComponent(id)}/reject`,
    SHORTLIST: (id) => `/execution-plans/${encodeURIComponent(id)}/shortlist`,
    WITHDRAW: (id) => `/execution-plans/${encodeURIComponent(id)}/withdraw`,
  }),
  MATCHES: Object.freeze({
    CHALLENGE_PROVIDERS: (challengeId) =>
      `/matches/challenge/${encodeURIComponent(challengeId)}/providers`,
    CHALLENGE_REFRESH: (challengeId) =>
      `/matches/challenge/${encodeURIComponent(challengeId)}/refresh`,
    CLIENT_DETAIL: (id) => `/matches/client/${encodeURIComponent(id)}`,
    CLIENT_STATUS: (id) => `/matches/client/${encodeURIComponent(id)}/status`,
    PROVIDER: "/matches/provider",
    PROVIDER_DETAIL: (id) => `/matches/provider/${encodeURIComponent(id)}`,
    PROVIDER_REFRESH: "/matches/provider/refresh",
    PROVIDER_STATUS: (id) => `/matches/provider/${encodeURIComponent(id)}/status`,
  }),
  FIRST_CLIENT: Object.freeze({
    BADGES: "/first-client/badges",
    REFRESH: "/first-client/refresh",
    STARTER_CHALLENGES: "/first-client/starter-challenges",
    STATUS: "/first-client/status",
  }),
  OUTCOME_OFFERS: Object.freeze({
    ARCHIVE: (id) => `/outcome-offers/${encodeURIComponent(id)}/archive`,
    BASE: "/outcome-offers",
    DETAIL_BY_ID: (id) => `/outcome-offers/id/${encodeURIComponent(id)}`,
    DETAIL_BY_SLUG: (username, slug) =>
      `/outcome-offers/${encodeURIComponent(username)}/${encodeURIComponent(slug)}`,
    MY: "/outcome-offers/me",
    PAUSE: (id) => `/outcome-offers/${encodeURIComponent(id)}/pause`,
    PUBLISH: (id) => `/outcome-offers/${encodeURIComponent(id)}/publish`,
  }),
  OPPORTUNITIES: Object.freeze({
    ARCHIVE: (id) => `/opportunities/${encodeURIComponent(id)}/archive`,
    BASE: "/opportunities",
    COMPLETE_NEXT_ACTION: (id) => `/opportunities/${encodeURIComponent(id)}/next-action/complete`,
    DETAIL: (id) => `/opportunities/${encodeURIComponent(id)}`,
    NEXT_ACTION: (id) => `/opportunities/${encodeURIComponent(id)}/next-action`,
    NOTES: (id) => `/opportunities/${encodeURIComponent(id)}/notes`,
    STAGE: (id) => `/opportunities/${encodeURIComponent(id)}/stage`,
    STATS: "/opportunities/stats",
  }),
  PROOF_ASSETS: Object.freeze({
    ATTACH: (id) => `/proof-assets/${encodeURIComponent(id)}/attach`,
    BASE: "/proof-assets",
    DETACH: (id) => `/proof-assets/${encodeURIComponent(id)}/detach`,
    DETAIL_BY_ID: (id) => `/proof-assets/id/${encodeURIComponent(id)}`,
    MY: "/proof-assets/me",
  }),
  PROVIDERS: Object.freeze({
    BASE: "/providers",
    COMPARE: "/providers/compare",
    FILTERS: "/providers/filters",
    PUBLIC_PROFILE: (username) => `/profile/${encodeURIComponent(username)}`,
  }),
  SAVED_PROVIDERS: Object.freeze({
    BASE: "/saved-providers",
    STATUS: (providerId) => `/saved-providers/provider/${encodeURIComponent(providerId)}/status`,
    UNSAVE: (providerId) => `/saved-providers/provider/${encodeURIComponent(providerId)}`,
  }),
  PROOFS: "/proofs",
  PROOF_LEDGER: "/proof-ledger",
  MESSAGES: "/messages",
  NOTIFICATIONS: "/notifications",
  ADMIN: Object.freeze({
    BASE: "/admin",
    CHALLENGES: "/admin/challenges",
    CHALLENGE_MODERATION: (id) => `/admin/challenges/${encodeURIComponent(id)}/moderation`,
    OFFERS: "/admin/outcome-offers",
    OFFER_MODERATION: (id) => `/admin/outcome-offers/${encodeURIComponent(id)}/moderation`,
    OVERVIEW: "/admin/overview",
    PROOF_ASSETS: "/admin/proof-assets",
    PROOF_ASSET_MODERATION: (id) => `/admin/proof-assets/${encodeURIComponent(id)}/moderation`,
    PROVIDERS: "/admin/providers",
    PROVIDER_MODERATION: (id) => `/admin/providers/${encodeURIComponent(id)}/moderation`,
    USERS: "/admin/users",
    USER_STATUS: (id) => `/admin/users/${encodeURIComponent(id)}/status`,
  }),
});

export const API_ENDPOINT_GROUPS = Object.freeze({
  AUTH: Object.freeze({
    LOGIN: API_ENDPOINTS.LOGIN,
    LOGOUT: API_ENDPOINTS.LOGOUT,
    ME: API_ENDPOINTS.ME,
    FORGOT_PASSWORD: API_ENDPOINTS.FORGOT_PASSWORD,
    REGISTER: API_ENDPOINTS.REGISTER,
    REFRESH_TOKEN: API_ENDPOINTS.REFRESH_TOKEN,
    RESET_PASSWORD: API_ENDPOINTS.RESET_PASSWORD,
    RESEND_VERIFICATION: API_ENDPOINTS.RESEND_VERIFICATION,
    STATUS: API_ENDPOINTS.AUTH_STATUS,
    VERIFY_EMAIL: API_ENDPOINTS.VERIFY_EMAIL,
    CHANGE_PASSWORD: API_ENDPOINTS.CHANGE_PASSWORD,
  }),
  HEALTH: Object.freeze({
    ROOT: API_ENDPOINTS.HEALTH,
    STATUS: API_ENDPOINTS.HEALTH_STATUS,
  }),
  USERS: Object.freeze({
    PROFILE: API_ENDPOINTS.PROFILE,
    STATUS: API_ENDPOINTS.USERS_STATUS,
  }),
  ADMIN: API_ENDPOINTS.ADMIN,
  PROFILE: Object.freeze({
    ABOUT: API_ENDPOINTS.PROFILE_ABOUT,
    ANALYTICS: API_ENDPOINTS.PROFILE_ANALYTICS,
    AVATAR: API_ENDPOINTS.PROFILE_AVATAR,
    COVER: API_ENDPOINTS.PROFILE_COVER,
    EDUCATION: API_ENDPOINTS.PROFILE_EDUCATION,
    EDUCATION_ITEM: API_ENDPOINTS.PROFILE_EDUCATION_ITEM,
    EXPERIENCE: API_ENDPOINTS.PROFILE_EXPERIENCE,
    EXPERIENCE_ITEM: API_ENDPOINTS.PROFILE_EXPERIENCE_ITEM,
    INTRO: API_ENDPOINTS.PROFILE_INTRO,
    ME: API_ENDPOINTS.PROFILE_ME,
    OPEN_TO: API_ENDPOINTS.PROFILE_OPEN_TO,
    PRIVACY: API_ENDPOINTS.PROFILE_PRIVACY,
    PUBLIC: API_ENDPOINTS.PROFILE,
    PUBLIC_ACTIVITY: API_ENDPOINTS.PROFILE_PUBLIC_ACTIVITY,
    PUBLIC_BY_USERNAME: API_ENDPOINTS.PROFILE_PUBLIC_BY_USERNAME,
    SERVICES: API_ENDPOINTS.PROFILE_SERVICES,
    SERVICE_ITEM: API_ENDPOINTS.PROFILE_SERVICE_ITEM,
    SKILLS: API_ENDPOINTS.PROFILE_SKILLS,
    UPDATE_ME: API_ENDPOINTS.PROFILE_UPDATE_ME,
    VERIFICATION: API_ENDPOINTS.PROFILE_VERIFICATION,
    VERIFICATION_REQUEST: API_ENDPOINTS.PROFILE_VERIFICATION_REQUEST,
  }),
  SOCIAL: Object.freeze({
    CONNECTION_REQUEST: API_ENDPOINTS.CONNECTION_REQUEST,
    CONNECTION_STATUS: API_ENDPOINTS.CONNECTION_STATUS,
    CONNECTION_WITH_USER: API_ENDPOINTS.CONNECTION_WITH_USER,
    FOLLOW_STATUS: API_ENDPOINTS.FOLLOW_STATUS,
    FOLLOW_USER: API_ENDPOINTS.FOLLOW_USER,
  }),
  CHALLENGES: API_ENDPOINTS.CHALLENGES,
  EXECUTION_PLANS: API_ENDPOINTS.EXECUTION_PLANS,
  FIRST_CLIENT: API_ENDPOINTS.FIRST_CLIENT,
  MATCHES: API_ENDPOINTS.MATCHES,
  OUTCOME_OFFERS: API_ENDPOINTS.OUTCOME_OFFERS,
  OPPORTUNITIES: API_ENDPOINTS.OPPORTUNITIES,
  PROOF_ASSETS: API_ENDPOINTS.PROOF_ASSETS,
  PROVIDERS: API_ENDPOINTS.PROVIDERS,
  SAVED_PROVIDERS: API_ENDPOINTS.SAVED_PROVIDERS,
});
