// @ts-check

import {
  ADMIN_NAV_LINKS,
} from "../config/navigation/adminNavigation.js";
import {
  CLIENT_NAV_GROUPS,
  CLIENT_NAV_LINKS,
} from "../config/navigation/clientNavigation.js";
import {
  COMPANY_NAV_LINKS,
  FOOTER_NAV_GROUPS,
  FOOTER_NAV_LINKS,
  MARKETPLACE_NAV_LINKS,
  PRODUCT_NAV_LINKS,
  PUBLIC_FOOTER_BRAND_COPY,
  PUBLIC_MOBILE_NAV_GROUPS,
  PUBLIC_NAV_DROPDOWNS,
  PUBLIC_NAV_LINKS,
  PUBLIC_NAV_REGISTRY,
  RESOURCE_NAV_LINKS,
} from "../config/navigation/publicNavigation.js";
import {
  PROVIDER_FUTURE_NAV_LINKS,
  PROVIDER_NAV_GROUPS,
  PROVIDER_NAV_LINKS,
} from "../config/navigation/providerNavigation.js";
import { ROUTE_IDS, ROUTE_METADATA } from "../config/routeMetadata.js";
import { canViewNavItem } from "../utils/accessPolicy.js";
import { createNavigationItemsFromRouteIds } from "../utils/routeHelpers.js";

const DASHBOARD_NAV_ROUTE_IDS = Object.freeze([
  ROUTE_IDS.DASHBOARD.DASHBOARD,
  ROUTE_IDS.CLIENT.WORKSPACE,
  ROUTE_IDS.CLIENT.CHALLENGES,
  ROUTE_IDS.PROVIDER.CHALLENGES,
  ROUTE_IDS.PROVIDER.FIRST_CLIENT,
  ROUTE_IDS.PROVIDER.OFFERS,
  ROUTE_IDS.PROVIDER.EXECUTION_PLANS,
  ROUTE_IDS.PROVIDER.OPPORTUNITIES,
  ROUTE_IDS.PROVIDER.PROOF_VAULT,
  ROUTE_IDS.CLIENT.PROVIDERS,
  ROUTE_IDS.DASHBOARD.PROFILE,
  ROUTE_IDS.DASHBOARD.PROOF,
  ROUTE_IDS.DASHBOARD.MESSAGES,
  ROUTE_IDS.DASHBOARD.NOTIFICATIONS,
  ROUTE_IDS.DASHBOARD.SAVED,
  ROUTE_IDS.DASHBOARD.BILLING,
  ROUTE_IDS.DASHBOARD.SETTINGS,
]);

export const DASHBOARD_NAV_LINKS = createNavigationItemsFromRouteIds(
  DASHBOARD_NAV_ROUTE_IDS,
  ROUTE_METADATA,
);

export const DASHBOARD_FUTURE_NAV_LINKS = Object.freeze(
  PROVIDER_FUTURE_NAV_LINKS.map((item) =>
    Object.freeze({
      ...item,
      comingSoon: true,
    }),
  ),
);

export {
  ADMIN_NAV_LINKS,
  CLIENT_NAV_GROUPS,
  CLIENT_NAV_LINKS,
  COMPANY_NAV_LINKS,
  FOOTER_NAV_GROUPS,
  FOOTER_NAV_LINKS,
  MARKETPLACE_NAV_LINKS,
  PRODUCT_NAV_LINKS,
  PROVIDER_NAV_GROUPS,
  PROVIDER_NAV_LINKS,
  PUBLIC_FOOTER_BRAND_COPY,
  PUBLIC_MOBILE_NAV_GROUPS,
  PUBLIC_NAV_DROPDOWNS,
  PUBLIC_NAV_LINKS,
  PUBLIC_NAV_REGISTRY,
  RESOURCE_NAV_LINKS,
};

export const NAVIGATION_GROUPS = Object.freeze({
  ADMIN: ADMIN_NAV_LINKS,
  CLIENT: CLIENT_NAV_LINKS,
  CLIENT_GROUPS: CLIENT_NAV_GROUPS,
  COMPANY: COMPANY_NAV_LINKS,
  DASHBOARD: DASHBOARD_NAV_LINKS,
  DASHBOARD_FUTURE: DASHBOARD_FUTURE_NAV_LINKS,
  FOOTER: FOOTER_NAV_LINKS,
  FOOTER_GROUPS: FOOTER_NAV_GROUPS,
  MARKETPLACE: MARKETPLACE_NAV_LINKS,
  PUBLIC: PUBLIC_NAV_LINKS,
  PUBLIC_DROPDOWNS: PUBLIC_NAV_DROPDOWNS,
  PUBLIC_MOBILE: PUBLIC_MOBILE_NAV_GROUPS,
  PRODUCT: PRODUCT_NAV_LINKS,
  PROVIDER: PROVIDER_NAV_LINKS,
  PROVIDER_GROUPS: PROVIDER_NAV_GROUPS,
  RESOURCES: RESOURCE_NAV_LINKS,
});

export function canAccessNavigationItem(item, role) {
  return canViewNavItem(item, role ? { id: role, role } : null, {
    isAuthenticated: Boolean(role),
    role,
  });
}
