export const ROUTES = Object.freeze({
  HOME: "/",
  HOW_IT_WORKS: "/how-it-works",
  CHALLENGES: "/challenges",
  PROVIDERS: "/providers",
  PROVIDER_COMPARE: "/providers/compare",
  PROOF_LEDGER: "/proof-ledger",
  LEADERBOARD: "/leaderboard",
  OUTCOME_OFFERS: "/offers",
  OUTCOME_OFFER_DETAIL: (username, slug) => `/offers/${encodeURIComponent(username)}/${encodeURIComponent(slug)}`,
  BLOG: "/blog",
  CONTACT: "/contact",
  RESOURCES: "/resources",
  CASE_STUDIES: "/case-studies",
  HELP: "/help",
  PRICING: "/pricing",
  PRIVACY: "/privacy",
  TERMS: "/terms",
  TRUST_SAFETY: "/trust-safety",

  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  VERIFY_EMAIL: "/verify-email",
  RESEND_VERIFICATION: "/resend-verification",

  DASHBOARD: "/dashboard",
  PROVIDER_DASHBOARD: "/dashboard/provider",
  CLIENT_WORKSPACE: "/dashboard/workspace",
  MY_CHALLENGES: "/dashboard/challenges",
  NEW_CHALLENGE: "/dashboard/challenges/new",
  OWNER_CHALLENGE: (challengeId) => `/dashboard/challenges/${encodeURIComponent(challengeId)}`,
  EDIT_CHALLENGE: (challengeId) => `/dashboard/challenges/${encodeURIComponent(challengeId)}/edit`,
  CHALLENGE_PROVIDERS: (challengeId) => `/dashboard/challenges/${encodeURIComponent(challengeId)}/providers`,
  CHALLENGE_SHORTLISTED_PROVIDERS: (challengeId) =>
    `/dashboard/challenges/${encodeURIComponent(challengeId)}/providers/shortlisted`,
  PROVIDER_SELECTION: (challengeId) =>
    `/dashboard/challenges/${encodeURIComponent(challengeId)}/provider-selection`,
  RECOMMENDED_PROVIDERS: (challengeId) => `/dashboard/challenges/${encodeURIComponent(challengeId)}/providers`,
  LEGACY_RECOMMENDED_PROVIDERS: (challengeId) =>
    `/dashboard/challenges/${encodeURIComponent(challengeId)}/recommended-providers`,
  CHALLENGE_PLANS: (challengeId) => `/dashboard/challenges/${encodeURIComponent(challengeId)}/plans`,
  CLIENT_EXECUTION_PLAN: (challengeId, planId) =>
    `/dashboard/challenges/${encodeURIComponent(challengeId)}/plans/${encodeURIComponent(planId)}`,
  MY_OUTCOME_OFFERS: "/dashboard/offers",
  NEW_OUTCOME_OFFER: "/dashboard/offers/new",
  OWNER_OUTCOME_OFFER: (offerId) => `/dashboard/offers/${encodeURIComponent(offerId)}`,
  EDIT_OUTCOME_OFFER: (offerId) => `/dashboard/offers/${encodeURIComponent(offerId)}/edit`,
  MY_EXECUTION_PLANS: "/dashboard/plans",
  NEW_EXECUTION_PLAN: "/dashboard/plans/new",
  EXECUTION_PLAN_DETAIL: (planId) => `/dashboard/plans/${encodeURIComponent(planId)}`,
  EDIT_EXECUTION_PLAN: (planId) => `/dashboard/plans/${encodeURIComponent(planId)}/edit`,
  MATCHED_CHALLENGES: "/dashboard/matches",
  SAVED_MATCHES: "/dashboard/matches/saved",
  APPLIED_MATCHES: "/dashboard/matches/applied",
  OPPORTUNITY_PIPELINE: "/dashboard/opportunities",
  OPPORTUNITY_DETAIL: (opportunityId) => `/dashboard/opportunities/${encodeURIComponent(opportunityId)}`,
  PROOF_VAULT: "/dashboard/proof-vault",
  PROOF_ASSET_DETAIL: (assetId) => `/dashboard/proof-vault/${encodeURIComponent(assetId)}`,
  FIRST_CLIENT_MODE: "/dashboard/first-client",
  STARTER_CHALLENGES: "/dashboard/starter-challenges",
  SAVED_PROVIDERS: "/dashboard/saved-providers",
  PROFILE: "/profile",
  PUBLIC_PROFILE: "/profile/:username",
  MESSAGES: "/messages",
  SETTINGS: "/settings",
  NOTIFICATIONS: "/notifications",
  PROOF: "/proof",
  SAVED: "/saved",
  BILLING: "/billing",

  ADMIN: "/admin",
  ADMIN_USERS: "/admin/users",
  ADMIN_PROVIDERS: "/admin/providers",
  ADMIN_CHALLENGES: "/admin/challenges",
  ADMIN_OFFERS: "/admin/offers",
  ADMIN_PROOF_ASSETS: "/admin/proof-assets",
  ADMIN_PROOF_REVIEW: "/admin/proof-review",
  ADMIN_REPORTS: "/admin/reports",
  ADMIN_VERIFICATION: "/admin/verification",
  ADMIN_DISPUTES: "/admin/disputes",
  ADMIN_SETTINGS: "/admin/settings",

  FORBIDDEN: "/403",
  SERVER_ERROR: "/500",

  ACCOUNT: "/account",
  CONNECTIONS: "/connections",
  LEADS: "/leads",
  MARKETPLACE: "/marketplace",
  NETWORK: "/network",
  PAYMENTS: "/payments",
  PORTFOLIO: "/portfolio",
  PROJECTS: "/projects",
  SCRAPER: "/scraper",
  SERVICES: "/services",
  PROVIDER_SERVICES: "/provider-services",
});
