import { Router } from "express";
import accountRoutes from "../accountRoutes.js";
import adminRoutes from "../adminRoutes.js";
import analyticsRoutes from "../analyticsRoutes.js";
import authRoutes from "./auth.routes.js";
import billingRoutes from "../billingRoutes.js";
import blogRoutes from "../blogRoutes.js";
import challengeRoutes from "./challenge.routes.js";
import connectionRoutes from "../connectionRoutes.js";
import conversationRoutes from "../conversationRoutes.js";
import contactRoutes from "../contactRoutes.js";
import executionPlanRoutes from "./executionPlan.routes.js";
import followRoutes from "../followRoutes.js";
import healthRoutes from "./health.routes.js";
import leadRoutes from "../leadRoutes.js";
import messageRoutes from "../messageRoutes.js";
import marketplacePaymentRoutes from "../marketplacePaymentRoutes.js";
import matchRoutes from "./match.routes.js";
import networkRoutes from "../networkRoutes.js";
import notificationRoutes from "../notificationRoutes.js";
import outcomeOfferRoutes from "./outcomeOffer.routes.js";
import portfolioRoutes from "../portfolioRoutes.js";
import providerRoutes from "../providerRoutes.js";
import profileRoutes from "./profile.routes.js";
import reviewRoutes from "../reviewRoutes.js";
import savedItemRoutes from "../savedItemRoutes.js";
import serviceRoutes from "../serviceRoutes.js";
import userRoutes from "./user.routes.js";

const router = Router();

router.use("/health", healthRoutes);
router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/account", accountRoutes);
router.use("/admin", adminRoutes);
router.use("/analytics", analyticsRoutes);
router.use("/billing", billingRoutes);
router.use("/blogs", blogRoutes);
router.use("/challenges", challengeRoutes);
router.use("/connections", connectionRoutes);
router.use("/conversations", conversationRoutes);
router.use("/contact", contactRoutes);
router.use("/execution-plans", executionPlanRoutes);
router.use("/follows", followRoutes);
router.use("/leads", leadRoutes);
router.use("/messages", messageRoutes);
router.use("/marketplace", marketplacePaymentRoutes);
router.use("/matches", matchRoutes);
router.use("/network", networkRoutes);
router.use("/notifications", notificationRoutes);
router.use("/outcome-offers", outcomeOfferRoutes);
router.use("/portfolio", portfolioRoutes);
router.use("/providers", providerRoutes);
router.use("/profile", profileRoutes);
router.use("/reviews", reviewRoutes);
router.use("/saved", savedItemRoutes);
router.use("/services", serviceRoutes);

export default router;
