// @ts-check

import {
  ADMIN_ROUTES,
  AUTH_ROUTES,
  CLIENT_ROUTES,
  DASHBOARD_ROUTES,
  DYNAMIC_ROUTES,
  PROVIDER_ROUTES,
  PUBLIC_ROUTES,
  SYSTEM_ROUTES,
} from "../constants/routes.js";
import { USER_ROLES } from "../constants/statuses.js";
import { ROUTE_GROUP } from "../types/routes.js";
import {
  assertUniqueRoutePaths,
  createRouteMap,
  getRouteByPath,
  getRoutesByGroup,
  isDynamicRoutePath,
} from "../utils/routeHelpers.js";

export const ROUTE_IDS = Object.freeze({
  PUBLIC: Object.freeze({
    HOME: "public.home",
    ABOUT: "public.about",
    HOW_IT_WORKS: "public.how_it_works",
    CHALLENGES: "public.challenges",
    PROVIDERS: "public.providers",
    PROOF_LEDGER: "public.proof_ledger",
    LEADERBOARD: "public.leaderboard",
    PRICING: "public.pricing",
    CONTACT: "public.contact",
    BLOG: "public.blog",
    RESOURCES: "public.resources",
    CASE_STUDIES: "public.case_studies",
    HELP: "public.help",
    TRUST_SAFETY: "public.trust_safety",
    PRIVACY: "public.privacy",
    TERMS: "public.terms",
  }),
  AUTH: Object.freeze({
    LOGIN: "auth.login",
    REGISTER: "auth.register",
    FORGOT_PASSWORD: "auth.forgot_password",
    RESET_PASSWORD: "auth.reset_password",
    VERIFY_EMAIL: "auth.verify_email",
    RESEND_VERIFICATION: "auth.resend_verification",
  }),
  DASHBOARD: Object.freeze({
    DASHBOARD: "dashboard.dashboard",
    CLIENT_DASHBOARD: "dashboard.client",
    PROVIDER_DASHBOARD: "dashboard.provider",
    SUPPORT_DASHBOARD: "dashboard.support",
    PROFILE: "dashboard.profile",
    MESSAGES: "dashboard.messages",
    NOTIFICATIONS: "dashboard.notifications",
    PROOF: "dashboard.proof",
    SAVED: "dashboard.saved",
    BILLING: "dashboard.billing",
    SETTINGS: "dashboard.settings",
  }),
  PROVIDER: Object.freeze({
    PROFILE: "provider.profile",
    PROFILE_ONBOARDING: "provider.profile_onboarding",
    PROFILE_ONBOARDING_STEP: "provider.profile_onboarding_step",
    OFFERS: "provider.offers",
    CHALLENGES: "provider.challenges",
    MATCHES: "provider.matches",
    PROOF_VAULT: "provider.proof_vault",
    OPPORTUNITIES: "provider.opportunities",
    FIRST_CLIENT: "provider.first_client",
    EXECUTION_PLANS: "provider.execution_plans",
    SETTINGS: "provider.settings",
  }),
  CLIENT: Object.freeze({
    DASHBOARD: "client.dashboard",
    WORKSPACE: "client.workspace",
    CHALLENGES: "client.challenges",
    PROVIDERS: "client.providers",
    ACTIVE: "client.active",
    SETTINGS: "client.settings",
  }),
  ADMIN: Object.freeze({
    DASHBOARD: "admin.dashboard",
    USERS: "admin.users",
    PROVIDERS: "admin.providers",
    CHALLENGES: "admin.challenges",
    OFFERS: "admin.offers",
    PROOF_ASSETS: "admin.proof_assets",
    PROOFS: "admin.proofs",
    REPORTS: "admin.reports",
    VERIFICATION: "admin.verification",
    DISPUTES: "admin.disputes",
    SETTINGS: "admin.settings",
  }),
  SYSTEM: Object.freeze({
    NOT_AUTHORIZED: "system.not_authorized",
    NOT_FOUND: "system.not_found",
    SERVER_ERROR: "system.server_error",
  }),
  DYNAMIC: Object.freeze({
    PUBLIC_PROFILE: "dynamic.public_profile",
    PROVIDER_PROFILE: "dynamic.provider_profile",
    PUBLIC_CHALLENGE: "dynamic.public_challenge",
    OWNER_CHALLENGE: "dynamic.owner_challenge",
    CHALLENGE_PLANS: "dynamic.challenge_plans",
    CHALLENGE_PROVIDERS: "dynamic.challenge_providers",
    EXECUTION_PLAN_DETAIL: "dynamic.execution_plan_detail",
    OUTCOME_OFFER_DETAIL: "dynamic.outcome_offer_detail",
    PROOF_ASSET_DETAIL: "dynamic.proof_asset_detail",
  }),
});

function route(config) {
  const roles = Object.freeze([...(config.roles ?? [])]);
  const permissions = Object.freeze([...(config.permissions ?? [])]);
  const futureFeatureFlags = Object.freeze([...(config.futureFeatureFlags ?? [])]);
  const breadcrumbLabel = config.breadcrumbLabel ?? config.label;

  return Object.freeze({
    breadcrumbLabel,
    description: config.description,
    futureAnalyticsId: config.futureAnalyticsId ?? config.id,
    futureFeatureFlags,
    futureMenuBadge: config.futureMenuBadge ?? "",
    futurePageTitle: config.futurePageTitle ?? config.label,
    futureSeoDescription: config.futureSeoDescription ?? config.description,
    futureSeoTitle: config.futureSeoTitle ?? config.label,
    futureTrackingId: config.futureTrackingId ?? config.id,
    group: config.group,
    iconKey: config.iconKey ?? "",
    id: config.id,
    isDynamic: isDynamicRoutePath(config.path),
    isProtected: Boolean(config.isProtected),
    isPublic: Boolean(config.isPublic),
    label: config.label,
    mobilePriority: config.mobilePriority ?? 100,
    path: config.path,
    permissions,
    roles,
    showInBreadcrumbs: config.showInBreadcrumbs ?? true,
    showInNavigation: Boolean(config.showInNavigation),
    showInSidebar: Boolean(config.showInSidebar),
  });
}

export const ROUTE_METADATA_LIST = Object.freeze([
  route({
    id: ROUTE_IDS.PUBLIC.HOME,
    path: PUBLIC_ROUTES.HOME,
    label: "Home",
    description: "ProofArena outcome economy overview.",
    group: ROUTE_GROUP.PUBLIC,
    iconKey: "Home",
    isPublic: true,
    showInNavigation: true,
    mobilePriority: 1,
  }),
  route({
    id: ROUTE_IDS.PUBLIC.ABOUT,
    path: PUBLIC_ROUTES.ABOUT,
    label: "About",
    description: "Learn about ScaleOps and the ProofArena outcome economy.",
    group: ROUTE_GROUP.PUBLIC,
    iconKey: "Info",
    isPublic: true,
    futureSeoTitle: "About ScaleOps and ProofArena",
  }),
  route({
    id: ROUTE_IDS.PUBLIC.HOW_IT_WORKS,
    path: PUBLIC_ROUTES.HOW_IT_WORKS,
    label: "How It Works",
    description: "See how measurable outcomes move from challenge to verified proof.",
    group: ROUTE_GROUP.PUBLIC,
    iconKey: "ListChecks",
    isPublic: true,
    showInNavigation: true,
    mobilePriority: 2,
  }),
  route({
    id: ROUTE_IDS.PUBLIC.CHALLENGES,
    path: PUBLIC_ROUTES.CHALLENGES,
    label: "Challenges",
    description: "Explore outcome challenges ready for execution plans.",
    group: ROUTE_GROUP.PUBLIC,
    iconKey: "Target",
    isPublic: true,
    showInNavigation: true,
    mobilePriority: 3,
  }),
  route({
    id: ROUTE_IDS.PUBLIC.PROVIDERS,
    path: PUBLIC_ROUTES.PROVIDERS,
    label: "Providers",
    description: "Discover providers building proof-based reputation.",
    group: ROUTE_GROUP.PUBLIC,
    iconKey: "Users",
    isPublic: true,
    showInNavigation: true,
    mobilePriority: 4,
  }),
  route({
    id: ROUTE_IDS.PUBLIC.PROOF_LEDGER,
    path: PUBLIC_ROUTES.PROOF_LEDGER,
    label: "Proof Ledger",
    description: "Review public records of verified outcome execution.",
    group: ROUTE_GROUP.PUBLIC,
    iconKey: "FileCheck2",
    isPublic: true,
    showInNavigation: true,
    mobilePriority: 5,
  }),
  route({
    id: ROUTE_IDS.PUBLIC.LEADERBOARD,
    path: PUBLIC_ROUTES.LEADERBOARD,
    label: "Leaderboard",
    description: "Explore provider rankings based on verified outcomes.",
    group: ROUTE_GROUP.PUBLIC,
    iconKey: "Medal",
    isPublic: true,
    showInNavigation: true,
    mobilePriority: 6,
  }),
  route({
    id: ROUTE_IDS.PUBLIC.PRICING,
    path: PUBLIC_ROUTES.PRICING,
    label: "Pricing",
    description: "Review outcome-focused platform pricing.",
    group: ROUTE_GROUP.PUBLIC,
    iconKey: "BadgeDollarSign",
    isPublic: true,
  }),
  route({
    id: ROUTE_IDS.PUBLIC.CONTACT,
    path: PUBLIC_ROUTES.CONTACT,
    label: "Contact",
    description: "Contact ScaleOps and the ProofArena team.",
    group: ROUTE_GROUP.PUBLIC,
    iconKey: "Mail",
    isPublic: true,
  }),
  route({
    id: ROUTE_IDS.PUBLIC.BLOG,
    path: PUBLIC_ROUTES.BLOG,
    label: "Blog",
    description: "Read product, marketplace, and outcome-economy insights.",
    group: ROUTE_GROUP.PUBLIC,
    iconKey: "Newspaper",
    isPublic: true,
  }),
  route({
    id: ROUTE_IDS.PUBLIC.RESOURCES,
    path: PUBLIC_ROUTES.RESOURCES,
    label: "Resources",
    description: "Explore guides, proof workflows, and marketplace resources.",
    group: ROUTE_GROUP.PUBLIC,
    iconKey: "BookOpen",
    isPublic: true,
  }),
  route({
    id: ROUTE_IDS.PUBLIC.CASE_STUDIES,
    path: PUBLIC_ROUTES.CASE_STUDIES,
    label: "Case Studies",
    description: "Review proof-backed outcome stories.",
    group: ROUTE_GROUP.PUBLIC,
    iconKey: "Library",
    isPublic: true,
  }),
  route({
    id: ROUTE_IDS.PUBLIC.HELP,
    path: PUBLIC_ROUTES.HELP,
    label: "Help Center",
    description: "Find support for clients, providers, and proof workflows.",
    group: ROUTE_GROUP.PUBLIC,
    iconKey: "LifeBuoy",
    isPublic: true,
  }),
  route({
    id: ROUTE_IDS.PUBLIC.TRUST_SAFETY,
    path: PUBLIC_ROUTES.TRUST_SAFETY,
    label: "Trust & Safety",
    description: "Understand ProofArena trust and safety foundations.",
    group: ROUTE_GROUP.PUBLIC,
    iconKey: "ShieldCheck",
    isPublic: true,
  }),
  route({
    id: ROUTE_IDS.PUBLIC.PRIVACY,
    path: PUBLIC_ROUTES.PRIVACY,
    label: "Privacy",
    description: "Review how profile, proof, and account data are handled.",
    group: ROUTE_GROUP.PUBLIC,
    iconKey: "LockKeyhole",
    isPublic: true,
  }),
  route({
    id: ROUTE_IDS.PUBLIC.TERMS,
    path: PUBLIC_ROUTES.TERMS,
    label: "Terms",
    description: "Review the platform terms of service.",
    group: ROUTE_GROUP.PUBLIC,
    iconKey: "ScrollText",
    isPublic: true,
  }),

  route({
    id: ROUTE_IDS.AUTH.LOGIN,
    path: AUTH_ROUTES.LOGIN,
    label: "Login",
    description: "Access an existing ProofArena account.",
    group: ROUTE_GROUP.AUTH,
    iconKey: "LogIn",
    isPublic: true,
    showInBreadcrumbs: false,
  }),
  route({
    id: ROUTE_IDS.AUTH.REGISTER,
    path: AUTH_ROUTES.REGISTER,
    label: "Register",
    description: "Create a client or provider ProofArena account.",
    group: ROUTE_GROUP.AUTH,
    iconKey: "UserPlus",
    isPublic: true,
    showInBreadcrumbs: false,
  }),
  route({
    id: ROUTE_IDS.AUTH.FORGOT_PASSWORD,
    path: AUTH_ROUTES.FORGOT_PASSWORD,
    label: "Forgot Password",
    description: "Request secure password reset instructions.",
    group: ROUTE_GROUP.AUTH,
    iconKey: "KeyRound",
    isPublic: true,
    showInBreadcrumbs: false,
  }),
  route({
    id: ROUTE_IDS.AUTH.RESET_PASSWORD,
    path: AUTH_ROUTES.RESET_PASSWORD,
    label: "Reset Password",
    description: "Create a new secure account password.",
    group: ROUTE_GROUP.AUTH,
    iconKey: "LockKeyhole",
    isPublic: true,
    showInBreadcrumbs: false,
  }),
  route({
    id: ROUTE_IDS.AUTH.VERIFY_EMAIL,
    path: AUTH_ROUTES.VERIFY_EMAIL,
    label: "Verify Email",
    description: "Verify account email ownership.",
    group: ROUTE_GROUP.AUTH,
    iconKey: "BadgeCheck",
    isPublic: true,
    showInBreadcrumbs: false,
  }),
  route({
    id: ROUTE_IDS.AUTH.RESEND_VERIFICATION,
    path: AUTH_ROUTES.RESEND_VERIFICATION,
    label: "Resend Verification",
    description: "Request a new email verification link.",
    group: ROUTE_GROUP.AUTH,
    iconKey: "Send",
    isPublic: true,
    showInBreadcrumbs: false,
  }),

  route({
    id: ROUTE_IDS.DASHBOARD.DASHBOARD,
    path: DASHBOARD_ROUTES.DASHBOARD,
    label: "Dashboard",
    description: "Authenticated ProofArena workspace overview.",
    group: ROUTE_GROUP.DASHBOARD,
    iconKey: "LayoutDashboard",
    isProtected: true,
    showInSidebar: true,
  }),
  route({
    id: ROUTE_IDS.DASHBOARD.CLIENT_DASHBOARD,
    path: DASHBOARD_ROUTES.CLIENT_DASHBOARD,
    label: "Client Dashboard Legacy",
    description: "Legacy client dashboard route retained for compatibility.",
    group: ROUTE_GROUP.CLIENT,
    iconKey: "LayoutDashboard",
    isProtected: true,
    roles: [USER_ROLES.CLIENT],
  }),
  route({
    id: ROUTE_IDS.DASHBOARD.PROVIDER_DASHBOARD,
    path: DASHBOARD_ROUTES.PROVIDER_DASHBOARD,
    label: "Provider Dashboard",
    description: "Provider acquisition home for matches, offers, proof assets, and opportunities.",
    group: ROUTE_GROUP.PROVIDER,
    iconKey: "LayoutDashboard",
    isProtected: true,
    roles: [USER_ROLES.PROVIDER],
  }),
  route({
    id: ROUTE_IDS.DASHBOARD.SUPPORT_DASHBOARD,
    path: DASHBOARD_ROUTES.SUPPORT_DASHBOARD,
    label: "Support Dashboard",
    description: "Support workspace for platform operations.",
    group: ROUTE_GROUP.DASHBOARD,
    iconKey: "LifeBuoy",
    isProtected: true,
    roles: [USER_ROLES.SUPPORT],
  }),
  route({
    id: ROUTE_IDS.CLIENT.DASHBOARD,
    path: CLIENT_ROUTES.DASHBOARD,
    label: "Client Overview",
    description: "Buyer control center for posted challenges, active work, saved providers, and next actions.",
    group: ROUTE_GROUP.CLIENT,
    iconKey: "LayoutDashboard",
    isProtected: true,
    roles: [USER_ROLES.CLIENT],
    showInSidebar: true,
  }),
  route({
    id: ROUTE_IDS.CLIENT.WORKSPACE,
    path: DASHBOARD_ROUTES.CLIENT_WORKSPACE,
    label: "Workspace",
    description: "Monitor active challenges, provider decisions, and next actions.",
    group: ROUTE_GROUP.CLIENT,
    iconKey: "BriefcaseBusiness",
    isProtected: true,
    roles: [USER_ROLES.CLIENT],
  }),
  route({
    id: ROUTE_IDS.CLIENT.CHALLENGES,
    path: CLIENT_ROUTES.CHALLENGES,
    label: "My Challenges",
    description: "Create and manage measurable outcome challenges with budget, timeline, proof requirements, and success criteria.",
    group: ROUTE_GROUP.CLIENT,
    iconKey: "Target",
    isProtected: true,
    roles: [USER_ROLES.CLIENT],
    showInSidebar: true,
  }),
  route({
    id: ROUTE_IDS.CLIENT.PROVIDERS,
    path: CLIENT_ROUTES.PROVIDERS,
    label: "Find Providers",
    description: "Discover and compare proof-backed providers by skill, category, proof score, reputation, and availability.",
    group: ROUTE_GROUP.CLIENT,
    iconKey: "Search",
    isProtected: true,
    roles: [USER_ROLES.CLIENT],
    showInSidebar: true,
  }),
  route({
    id: ROUTE_IDS.CLIENT.ACTIVE,
    path: CLIENT_ROUTES.ACTIVE,
    label: "Active Work",
    description: "Track active outcomes, milestones, proof submissions, approvals, and revisions.",
    group: ROUTE_GROUP.CLIENT,
    iconKey: "BriefcaseBusiness",
    isProtected: true,
    roles: [USER_ROLES.CLIENT],
    showInSidebar: true,
  }),
  route({
    id: ROUTE_IDS.CLIENT.SETTINGS,
    path: CLIENT_ROUTES.SETTINGS,
    label: "Settings",
    description: "Manage client account, company profile, verification, notifications, billing, and preferences.",
    group: ROUTE_GROUP.CLIENT,
    iconKey: "Settings",
    isProtected: true,
    roles: [USER_ROLES.CLIENT],
    showInSidebar: true,
  }),
  route({
    id: ROUTE_IDS.PROVIDER.CHALLENGES,
    path: PROVIDER_ROUTES.CHALLENGES,
    label: "Matched Challenges",
    description: "Review warm outcome challenges matched to your offers and proof profile.",
    group: ROUTE_GROUP.PROVIDER,
    iconKey: "Target",
    isProtected: true,
    roles: [USER_ROLES.PROVIDER],
    showInSidebar: true,
  }),
  route({
    id: ROUTE_IDS.PROVIDER.MATCHES,
    path: DASHBOARD_ROUTES.MATCHED_CHALLENGES,
    label: "Matched Challenges",
    description: "Legacy matched challenge workspace route retained for existing provider links.",
    group: ROUTE_GROUP.PROVIDER,
    iconKey: "Target",
    isProtected: true,
    roles: [USER_ROLES.PROVIDER],
  }),
  route({
    id: ROUTE_IDS.PROVIDER.FIRST_CLIENT,
    path: DASHBOARD_ROUTES.FIRST_CLIENT_MODE,
    label: "First Client Mode",
    description: "Follow the guided path toward your first proof-backed client win.",
    group: ROUTE_GROUP.PROVIDER,
    iconKey: "Medal",
    isProtected: true,
    roles: [USER_ROLES.PROVIDER],
    showInSidebar: true,
  }),
  route({
    id: ROUTE_IDS.PROVIDER.OFFERS,
    path: PROVIDER_ROUTES.OFFERS,
    label: "Outcome Offers",
    description: "Package services into measurable proof-based offers.",
    group: ROUTE_GROUP.PROVIDER,
    iconKey: "PackageCheck",
    isProtected: true,
    roles: [USER_ROLES.PROVIDER],
    showInSidebar: true,
  }),
  route({
    id: ROUTE_IDS.PROVIDER.EXECUTION_PLANS,
    path: DASHBOARD_ROUTES.MY_EXECUTION_PLANS,
    label: "Execution Plans",
    description: "Track structured plans submitted to client challenges.",
    group: ROUTE_GROUP.PROVIDER,
    iconKey: "ClipboardList",
    isProtected: true,
    roles: [USER_ROLES.PROVIDER],
    showInSidebar: true,
  }),
  route({
    id: ROUTE_IDS.PROVIDER.OPPORTUNITIES,
    path: PROVIDER_ROUTES.OPPORTUNITIES,
    label: "Opportunity Pipeline",
    description: "Manage matched, applied, shortlisted, won, and lost client opportunities.",
    group: ROUTE_GROUP.PROVIDER,
    iconKey: "ClipboardList",
    isProtected: true,
    roles: [USER_ROLES.PROVIDER],
    showInSidebar: true,
  }),
  route({
    id: ROUTE_IDS.PROVIDER.PROOF_VAULT,
    path: PROVIDER_ROUTES.PROOF_VAULT,
    label: "Proof Vault",
    description: "Store reusable proof assets for offers and execution plans.",
    group: ROUTE_GROUP.PROVIDER,
    iconKey: "FileCheck2",
    isProtected: true,
    roles: [USER_ROLES.PROVIDER],
    showInSidebar: true,
  }),
  route({
    id: ROUTE_IDS.PROVIDER.PROFILE,
    path: PROVIDER_ROUTES.PROFILE,
    label: "Provider Profile",
    description: "Manage the client-ready provider identity system and onboarding progress.",
    group: ROUTE_GROUP.PROVIDER,
    iconKey: "UserCircle",
    isProtected: true,
    roles: [USER_ROLES.PROVIDER],
    showInBreadcrumbs: true,
  }),
  route({
    id: ROUTE_IDS.PROVIDER.PROFILE_ONBOARDING,
    path: PROVIDER_ROUTES.PROFILE_ONBOARDING,
    label: "Profile Onboarding",
    description: "Work through the enhanced provider profile onboarding flow.",
    group: ROUTE_GROUP.PROVIDER,
    iconKey: "ListChecks",
    isProtected: true,
    roles: [USER_ROLES.PROVIDER],
    showInBreadcrumbs: true,
  }),
  route({
    id: ROUTE_IDS.PROVIDER.PROFILE_ONBOARDING_STEP,
    path: PROVIDER_ROUTES.PROFILE_ONBOARDING_STEP,
    label: "Profile Step",
    description: "Edit one enhanced profile onboarding step.",
    group: ROUTE_GROUP.PROVIDER,
    iconKey: "ClipboardCheck",
    isProtected: true,
    roles: [USER_ROLES.PROVIDER],
    showInBreadcrumbs: true,
  }),
  route({
    id: ROUTE_IDS.PROVIDER.SETTINGS,
    path: PROVIDER_ROUTES.SETTINGS,
    label: "Settings",
    description: "Account, profile, notification, availability, and provider preference controls.",
    group: ROUTE_GROUP.PROVIDER,
    iconKey: "Settings",
    isProtected: true,
    roles: [USER_ROLES.PROVIDER],
    showInSidebar: true,
  }),
  route({
    id: ROUTE_IDS.DASHBOARD.PROFILE,
    path: DASHBOARD_ROUTES.PROFILE,
    label: "Profile",
    description: "Manage your identity and proof-based reputation.",
    group: ROUTE_GROUP.DASHBOARD,
    iconKey: "UserCircle",
    isProtected: true,
    showInSidebar: true,
  }),
  route({
    id: ROUTE_IDS.DASHBOARD.PROOF,
    path: DASHBOARD_ROUTES.PROOF,
    label: "Proof",
    description: "Review your submitted proof and verification status.",
    group: ROUTE_GROUP.DASHBOARD,
    iconKey: "FileCheck2",
    isProtected: true,
    showInSidebar: true,
  }),
  route({
    id: ROUTE_IDS.DASHBOARD.MESSAGES,
    path: DASHBOARD_ROUTES.MESSAGES,
    label: "Messages",
    description: "Coordinate execution with clients and providers.",
    group: ROUTE_GROUP.DASHBOARD,
    iconKey: "MessageSquare",
    isProtected: true,
    showInSidebar: true,
  }),
  route({
    id: ROUTE_IDS.DASHBOARD.NOTIFICATIONS,
    path: DASHBOARD_ROUTES.NOTIFICATIONS,
    label: "Notifications",
    description: "Review challenge updates, proof alerts, and message signals.",
    group: ROUTE_GROUP.DASHBOARD,
    iconKey: "Bell",
    isProtected: true,
    showInSidebar: true,
  }),
  route({
    id: ROUTE_IDS.DASHBOARD.SAVED,
    path: DASHBOARD_ROUTES.SAVED,
    label: "Saved",
    description: "Keep saved providers, challenges, and proof records together.",
    group: ROUTE_GROUP.DASHBOARD,
    iconKey: "Bookmark",
    isProtected: true,
    showInSidebar: true,
  }),
  route({
    id: ROUTE_IDS.DASHBOARD.BILLING,
    path: DASHBOARD_ROUTES.BILLING,
    label: "Billing",
    description: "Manage invoices, provider earnings, and future payments.",
    group: ROUTE_GROUP.DASHBOARD,
    iconKey: "CreditCard",
    isProtected: true,
    showInSidebar: true,
  }),
  route({
    id: ROUTE_IDS.DASHBOARD.SETTINGS,
    path: DASHBOARD_ROUTES.SETTINGS,
    label: "Settings",
    description: "Configure workspace preferences.",
    group: ROUTE_GROUP.DASHBOARD,
    iconKey: "Settings",
    isProtected: true,
    showInSidebar: true,
  }),

  route({
    id: ROUTE_IDS.ADMIN.DASHBOARD,
    path: ADMIN_ROUTES.ADMIN,
    label: "Admin Overview",
    description: "Platform trust and operations overview.",
    group: ROUTE_GROUP.ADMIN,
    iconKey: "LayoutDashboard",
    isProtected: true,
    roles: [USER_ROLES.ADMIN],
    showInSidebar: true,
  }),
  route({
    id: ROUTE_IDS.ADMIN.USERS,
    path: ADMIN_ROUTES.ADMIN_USERS,
    label: "Users",
    description: "Review users and account status.",
    group: ROUTE_GROUP.ADMIN,
    iconKey: "Users",
    isProtected: true,
    roles: [USER_ROLES.ADMIN],
    showInSidebar: true,
  }),
  route({
    id: ROUTE_IDS.ADMIN.PROVIDERS,
    path: ADMIN_ROUTES.ADMIN_PROVIDERS,
    label: "Providers",
    description: "Manage provider verification and quality.",
    group: ROUTE_GROUP.ADMIN,
    iconKey: "ShieldCheck",
    isProtected: true,
    roles: [USER_ROLES.ADMIN],
    showInSidebar: true,
  }),
  route({
    id: ROUTE_IDS.ADMIN.CHALLENGES,
    path: ADMIN_ROUTES.ADMIN_CHALLENGES,
    label: "Challenges",
    description: "Moderate outcome challenge quality.",
    group: ROUTE_GROUP.ADMIN,
    iconKey: "Target",
    isProtected: true,
    roles: [USER_ROLES.ADMIN],
    showInSidebar: true,
  }),
  route({
    id: ROUTE_IDS.ADMIN.OFFERS,
    path: ADMIN_ROUTES.ADMIN_OFFERS,
    label: "Outcome Offers",
    description: "Moderate published and draft outcome offers.",
    group: ROUTE_GROUP.ADMIN,
    iconKey: "PackageCheck",
    isProtected: true,
    roles: [USER_ROLES.ADMIN],
    showInSidebar: true,
  }),
  route({
    id: ROUTE_IDS.ADMIN.PROOF_ASSETS,
    path: ADMIN_ROUTES.ADMIN_PROOF_ASSETS,
    label: "Proof Assets",
    description: "Review proof assets and verification signals.",
    group: ROUTE_GROUP.ADMIN,
    iconKey: "FileCheck2",
    isProtected: true,
    roles: [USER_ROLES.ADMIN],
    showInSidebar: true,
  }),
  route({
    id: ROUTE_IDS.ADMIN.PROOFS,
    path: ADMIN_ROUTES.ADMIN_PROOFS,
    label: "Proof Reviews",
    description: "Review submitted proof before outcomes become public reputation.",
    group: ROUTE_GROUP.ADMIN,
    iconKey: "FileSearch",
    isProtected: true,
    roles: [USER_ROLES.ADMIN],
    showInSidebar: true,
  }),
  route({
    id: ROUTE_IDS.ADMIN.VERIFICATION,
    path: ADMIN_ROUTES.ADMIN_VERIFICATION,
    label: "Verification",
    description: "Review provider identity and profile verification requests.",
    group: ROUTE_GROUP.ADMIN,
    iconKey: "BadgeCheck",
    isProtected: true,
    roles: [USER_ROLES.ADMIN],
    showInSidebar: true,
  }),
  route({
    id: ROUTE_IDS.ADMIN.REPORTS,
    path: ADMIN_ROUTES.ADMIN_REPORTS,
    label: "Reports",
    description: "Inspect platform trust reports.",
    group: ROUTE_GROUP.ADMIN,
    iconKey: "BarChart3",
    isProtected: true,
    roles: [USER_ROLES.ADMIN],
    showInSidebar: true,
  }),
  route({
    id: ROUTE_IDS.ADMIN.DISPUTES,
    path: ADMIN_ROUTES.ADMIN_DISPUTES,
    label: "Disputes",
    description: "Handle disputes and trust escalations.",
    group: ROUTE_GROUP.ADMIN,
    iconKey: "AlertTriangle",
    isProtected: true,
    roles: [USER_ROLES.ADMIN],
    showInSidebar: true,
  }),
  route({
    id: ROUTE_IDS.ADMIN.SETTINGS,
    path: ADMIN_ROUTES.ADMIN_SETTINGS,
    label: "Settings",
    description: "Configure platform controls.",
    group: ROUTE_GROUP.ADMIN,
    iconKey: "Settings",
    isProtected: true,
    roles: [USER_ROLES.ADMIN],
    showInSidebar: true,
  }),

  route({
    id: ROUTE_IDS.SYSTEM.NOT_AUTHORIZED,
    path: SYSTEM_ROUTES.NOT_AUTHORIZED,
    label: "Not Authorized",
    description: "Route for users who do not have access to a protected area.",
    group: ROUTE_GROUP.SYSTEM,
    iconKey: "ShieldAlert",
    isPublic: true,
  }),
  route({
    id: ROUTE_IDS.SYSTEM.NOT_FOUND,
    path: SYSTEM_ROUTES.NOT_FOUND,
    label: "Not Found",
    description: "Route for unavailable pages.",
    group: ROUTE_GROUP.SYSTEM,
    iconKey: "CircleAlert",
    isPublic: true,
  }),
  route({
    id: ROUTE_IDS.SYSTEM.SERVER_ERROR,
    path: SYSTEM_ROUTES.SERVER_ERROR,
    label: "Server Error",
    description: "Route for unexpected application failures.",
    group: ROUTE_GROUP.SYSTEM,
    iconKey: "CircleX",
    isPublic: true,
  }),

  route({
    id: ROUTE_IDS.DYNAMIC.PUBLIC_PROFILE,
    path: DYNAMIC_ROUTES.PUBLIC_PROFILE,
    label: "Public Profile",
    description: "Public-safe profile page.",
    group: ROUTE_GROUP.DYNAMIC,
    iconKey: "UserCircle",
    isPublic: true,
  }),
  route({
    id: ROUTE_IDS.DYNAMIC.PROVIDER_PROFILE,
    path: DYNAMIC_ROUTES.PROVIDER_PROFILE,
    label: "Provider Profile",
    description: "Public provider profile page.",
    group: ROUTE_GROUP.DYNAMIC,
    iconKey: "Users",
    isPublic: true,
  }),
  route({
    id: ROUTE_IDS.DYNAMIC.PUBLIC_CHALLENGE,
    path: DYNAMIC_ROUTES.PUBLIC_CHALLENGE,
    label: "Challenge",
    description: "Public outcome challenge detail page.",
    group: ROUTE_GROUP.DYNAMIC,
    iconKey: "Target",
    isPublic: true,
  }),
  route({
    id: ROUTE_IDS.DYNAMIC.OWNER_CHALLENGE,
    path: DYNAMIC_ROUTES.OWNER_CHALLENGE,
    label: "Challenge Control Panel",
    description: "Client-owned challenge management route.",
    group: ROUTE_GROUP.DYNAMIC,
    iconKey: "Target",
    isProtected: true,
    roles: [USER_ROLES.CLIENT],
  }),
  route({
    id: ROUTE_IDS.DYNAMIC.CHALLENGE_PROVIDERS,
    path: DYNAMIC_ROUTES.CHALLENGE_PROVIDERS,
    label: "Challenge Providers",
    description: "Client provider-selection center for a challenge.",
    group: ROUTE_GROUP.DYNAMIC,
    iconKey: "Users",
    isProtected: true,
    roles: [USER_ROLES.CLIENT],
  }),
  route({
    id: ROUTE_IDS.DYNAMIC.CHALLENGE_PLANS,
    path: DYNAMIC_ROUTES.CHALLENGE_PLANS,
    label: "Challenge Plans",
    description: "Execution plan review route for a client challenge.",
    group: ROUTE_GROUP.DYNAMIC,
    iconKey: "ClipboardList",
    isProtected: true,
    roles: [USER_ROLES.CLIENT],
  }),
  route({
    id: ROUTE_IDS.DYNAMIC.EXECUTION_PLAN_DETAIL,
    path: DYNAMIC_ROUTES.EXECUTION_PLAN_DETAIL,
    label: "Execution Plan",
    description: "Provider-owned execution plan detail route.",
    group: ROUTE_GROUP.DYNAMIC,
    iconKey: "ClipboardList",
    isProtected: true,
    roles: [USER_ROLES.PROVIDER],
  }),
  route({
    id: ROUTE_IDS.DYNAMIC.OUTCOME_OFFER_DETAIL,
    path: DYNAMIC_ROUTES.OWNER_OUTCOME_OFFER,
    label: "Outcome Offer",
    description: "Provider-owned outcome offer detail route.",
    group: ROUTE_GROUP.DYNAMIC,
    iconKey: "PackageCheck",
    isProtected: true,
    roles: [USER_ROLES.PROVIDER],
  }),
  route({
    id: ROUTE_IDS.DYNAMIC.PROOF_ASSET_DETAIL,
    path: DYNAMIC_ROUTES.PROOF_ASSET_DETAIL,
    label: "Proof Asset",
    description: "Provider-owned proof asset detail route.",
    group: ROUTE_GROUP.DYNAMIC,
    iconKey: "FileCheck2",
    isProtected: true,
    roles: [USER_ROLES.PROVIDER],
  }),
]);

export const ROUTE_METADATA = createRouteMap(ROUTE_METADATA_LIST);
export const ROUTE_DUPLICATE_PATHS = assertUniqueRoutePaths(ROUTE_METADATA_LIST);

export function getRouteMetadata(routeId) {
  return ROUTE_METADATA[routeId] ?? null;
}

export function getRouteMetadataByPath(pathname) {
  return getRouteByPath(ROUTE_METADATA_LIST, pathname);
}

export function getRouteMetadataByGroup(group) {
  return getRoutesByGroup(ROUTE_METADATA_LIST, group);
}
