// @ts-check

import {
  PROFILE_PRIVACY_LEVEL,
  PROFILE_SECTION_KEY,
} from "../../types/profile.js";
import { PROFILE_ONBOARDING_STEP_IDS } from "./profileSections.js";

function step(config) {
  return Object.freeze({
    ...config,
    dependsOn: Object.freeze(config.dependsOn ?? []),
    fields: Object.freeze(config.fields ?? []),
    unlocks: Object.freeze(config.unlocks ?? []),
  });
}

/** @type {readonly import("../../types/profile.js").ProfileOnboardingStep[]} */
export const PROFILE_ONBOARDING_STEPS = Object.freeze([
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.ACCOUNT_TYPE,
    order: 1,
    section: PROFILE_SECTION_KEY.IDENTITY,
    title: "Account Type",
    shortLabel: "Account",
    description: "Classify the profile owner as an individual provider, agency, organization, or admin-managed account.",
    routeSegment: "account-type",
    required: true,
    skippable: false,
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.PERSONAL_INFORMATION],
    estimatedMinutes: 2,
    fields: ["identity.accountType"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PRIVATE,
    stageDependency: "stage_4_profile_foundation",
    completionWeight: 2,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.PERSONAL_INFORMATION,
    order: 2,
    section: PROFILE_SECTION_KEY.IDENTITY,
    title: "Personal Information",
    shortLabel: "Personal",
    description: "Collect display name, first name, last name, username, timezone, language, and public identity basics.",
    routeSegment: "personal-information",
    required: true,
    skippable: false,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.ACCOUNT_TYPE],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.PROFILE_PHOTO],
    estimatedMinutes: 4,
    fields: ["identity.displayName", "identity.firstName", "identity.lastName", "identity.username", "identity.timezone", "identity.language"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.MIXED,
    stageDependency: "stage_4_profile_foundation",
    completionWeight: 3,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.PROFILE_PHOTO,
    order: 3,
    section: PROFILE_SECTION_KEY.IDENTITY,
    title: "Profile Photo",
    shortLabel: "Photo",
    description: "Reserve the avatar step for a future upload workflow without creating upload behavior yet.",
    routeSegment: "profile-photo",
    required: false,
    skippable: true,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.PERSONAL_INFORMATION],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.COVER_BANNER],
    estimatedMinutes: 3,
    fields: ["identity.avatarUrl"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PUBLIC,
    futureFeature: "profile_media_upload",
    stageDependency: "stage_4_media_upload_later",
    completionWeight: 2,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.COVER_BANNER,
    order: 4,
    section: PROFILE_SECTION_KEY.IDENTITY,
    title: "Cover Banner",
    shortLabel: "Cover",
    description: "Reserve the profile cover banner step for future brand and trust presentation.",
    routeSegment: "cover-banner",
    required: false,
    skippable: true,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.PROFILE_PHOTO],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.CONTACT_INFORMATION],
    estimatedMinutes: 3,
    fields: ["identity.coverUrl"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PUBLIC,
    futureFeature: "profile_media_upload",
    stageDependency: "stage_4_media_upload_later",
    completionWeight: 1,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.CONTACT_INFORMATION,
    order: 5,
    section: PROFILE_SECTION_KEY.IDENTITY,
    title: "Contact Information",
    shortLabel: "Contact",
    description: "Capture private contact email, phone, location, and timezone fields without exposing them publicly by default.",
    routeSegment: "contact-information",
    required: true,
    skippable: false,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.PERSONAL_INFORMATION],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.PROFESSIONAL_HEADLINE],
    estimatedMinutes: 4,
    fields: ["identity.contactEmail", "identity.contactPhone", "identity.location", "identity.timezone"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PRIVATE,
    stageDependency: "stage_4_profile_foundation",
    completionWeight: 2,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.PROFESSIONAL_HEADLINE,
    order: 6,
    section: PROFILE_SECTION_KEY.PROFESSIONAL_IDENTITY,
    title: "Professional Headline",
    shortLabel: "Headline",
    description: "Define the concise client-facing positioning statement for the provider.",
    routeSegment: "professional-headline",
    required: true,
    skippable: false,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.CONTACT_INFORMATION],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.BIO],
    estimatedMinutes: 4,
    fields: ["professionalIdentity.headline"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PUBLIC,
    stageDependency: "stage_4_profile_foundation",
    completionWeight: 3,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.BIO,
    order: 7,
    section: PROFILE_SECTION_KEY.PROFESSIONAL_IDENTITY,
    title: "Bio",
    shortLabel: "Bio",
    description: "Prepare the provider narrative, credibility framing, and outcome-focused positioning.",
    routeSegment: "bio",
    required: true,
    skippable: false,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.PROFESSIONAL_HEADLINE],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.INDUSTRY],
    estimatedMinutes: 8,
    fields: ["professionalIdentity.bio"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PUBLIC,
    stageDependency: "stage_4_profile_foundation",
    completionWeight: 4,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.INDUSTRY,
    order: 8,
    section: PROFILE_SECTION_KEY.PROFESSIONAL_IDENTITY,
    title: "Industry",
    shortLabel: "Industry",
    description: "Classify the provider's primary industry for discovery and matching readiness.",
    routeSegment: "industry",
    required: true,
    skippable: false,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.BIO],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.NICHE],
    estimatedMinutes: 3,
    fields: ["professionalIdentity.industry"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PUBLIC,
    stageDependency: "stage_4_profile_foundation",
    completionWeight: 2,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.NICHE,
    order: 9,
    section: PROFILE_SECTION_KEY.PROFESSIONAL_IDENTITY,
    title: "Niche",
    shortLabel: "Niche",
    description: "Capture the specific market, domain, or outcome niche the provider serves best.",
    routeSegment: "niche",
    required: true,
    skippable: false,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.INDUSTRY],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.TARGET_CLIENT],
    estimatedMinutes: 4,
    fields: ["professionalIdentity.niche"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PUBLIC,
    stageDependency: "stage_4_profile_foundation",
    completionWeight: 2,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.TARGET_CLIENT,
    order: 10,
    section: PROFILE_SECTION_KEY.PROFESSIONAL_IDENTITY,
    title: "Target Client",
    shortLabel: "Client",
    description: "Describe the client segment the provider can serve with measurable outcomes.",
    routeSegment: "target-client",
    required: true,
    skippable: false,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.NICHE],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.SKILLS],
    estimatedMinutes: 4,
    fields: ["professionalIdentity.targetClient"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PUBLIC,
    stageDependency: "stage_4_profile_foundation",
    completionWeight: 3,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.SKILLS,
    order: 11,
    section: PROFILE_SECTION_KEY.SKILLS,
    title: "Skills",
    shortLabel: "Skills",
    description: "Capture primary skills that will later power public profile, matching, and proof associations.",
    routeSegment: "skills",
    required: true,
    skippable: false,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.TARGET_CLIENT],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.TOOLS],
    estimatedMinutes: 6,
    fields: ["skills.skills"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PUBLIC,
    stageDependency: "stage_4_profile_foundation",
    completionWeight: 4,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.TOOLS,
    order: 12,
    section: PROFILE_SECTION_KEY.SKILLS,
    title: "Tools",
    shortLabel: "Tools",
    description: "Capture software and workflow tools relevant to provider delivery credibility.",
    routeSegment: "tools",
    required: false,
    skippable: true,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.SKILLS],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.PLATFORMS],
    estimatedMinutes: 4,
    fields: ["skills.tools"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PUBLIC,
    stageDependency: "stage_4_profile_foundation",
    completionWeight: 2,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.PLATFORMS,
    order: 13,
    section: PROFILE_SECTION_KEY.SKILLS,
    title: "Platforms",
    shortLabel: "Platforms",
    description: "Capture platforms, ecosystems, and channels where the provider can execute.",
    routeSegment: "platforms",
    required: false,
    skippable: true,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.TOOLS],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.EXPERIENCE_LEVELS],
    estimatedMinutes: 4,
    fields: ["skills.platforms"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PUBLIC,
    stageDependency: "stage_4_profile_foundation",
    completionWeight: 2,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.EXPERIENCE_LEVELS,
    order: 14,
    section: PROFILE_SECTION_KEY.SKILLS,
    title: "Experience Levels",
    shortLabel: "Levels",
    description: "Map skills to experience levels for future matching and profile strength signals.",
    routeSegment: "experience-levels",
    required: true,
    skippable: false,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.SKILLS],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.SKILL_VERIFICATION],
    estimatedMinutes: 5,
    fields: ["skills.skillLevels", "professionalIdentity.experienceLevel", "professionalIdentity.yearsOfExperience"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PUBLIC,
    stageDependency: "stage_4_profile_foundation",
    completionWeight: 3,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.SKILL_VERIFICATION,
    order: 15,
    section: PROFILE_SECTION_KEY.SKILLS,
    title: "Skill Verification",
    shortLabel: "Verify",
    description: "Reserve future skill verification status without granting verified skill claims yet.",
    routeSegment: "skill-verification",
    required: false,
    skippable: true,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.EXPERIENCE_LEVELS],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.SERVICE_CATEGORIES],
    estimatedMinutes: 3,
    fields: ["skills.verifiedSkills"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.MIXED,
    futureFeature: "skill_verification_workflow",
    stageDependency: "future_verification_stage",
    completionWeight: 1,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.SERVICE_CATEGORIES,
    order: 16,
    section: PROFILE_SECTION_KEY.SERVICES,
    title: "Service Categories",
    shortLabel: "Categories",
    description: "Connect provider skills to service categories clients can understand and compare.",
    routeSegment: "service-categories",
    required: true,
    skippable: false,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.SKILLS],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.OUTCOME_OFFERS],
    estimatedMinutes: 5,
    fields: ["skills.serviceCategories", "services.services"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PUBLIC,
    stageDependency: "stage_4_profile_foundation",
    completionWeight: 3,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.OUTCOME_OFFERS,
    order: 17,
    section: PROFILE_SECTION_KEY.SERVICES,
    title: "Outcome Offers",
    shortLabel: "Offers",
    description: "Reserve connection points to measurable outcome offers without building offer CRUD in this prompt.",
    routeSegment: "outcome-offers",
    required: false,
    skippable: true,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.SERVICE_CATEGORIES],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.PRICING_MODELS],
    estimatedMinutes: 5,
    fields: ["services.outcomeOfferRefs"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PUBLIC,
    futureFeature: "outcome_offer_connection",
    stageDependency: "stage_10_outcome_offers",
    completionWeight: 2,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.PRICING_MODELS,
    order: 18,
    section: PROFILE_SECTION_KEY.SERVICES,
    title: "Pricing Models",
    shortLabel: "Pricing",
    description: "Prepare pricing model choices for future offer packaging and buyer expectations.",
    routeSegment: "pricing-models",
    required: false,
    skippable: true,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.SERVICE_CATEGORIES],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.DELIVERY_TIMELINES],
    estimatedMinutes: 4,
    fields: ["services.pricingModels"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.MIXED,
    stageDependency: "stage_4_profile_foundation",
    completionWeight: 2,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.DELIVERY_TIMELINES,
    order: 19,
    section: PROFILE_SECTION_KEY.SERVICES,
    title: "Delivery Timelines",
    shortLabel: "Timelines",
    description: "Capture expected delivery windows for service readiness and future matching.",
    routeSegment: "delivery-timelines",
    required: true,
    skippable: false,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.SERVICE_CATEGORIES],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.REVISION_POLICIES],
    estimatedMinutes: 4,
    fields: ["services.deliveryTimelines"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PUBLIC,
    stageDependency: "stage_4_profile_foundation",
    completionWeight: 3,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.REVISION_POLICIES,
    order: 20,
    section: PROFILE_SECTION_KEY.SERVICES,
    title: "Revision Policies",
    shortLabel: "Revisions",
    description: "Prepare client expectation fields for revision boundaries and delivery clarity.",
    routeSegment: "revision-policies",
    required: false,
    skippable: true,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.DELIVERY_TIMELINES],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.PORTFOLIO],
    estimatedMinutes: 4,
    fields: ["services.revisionPolicies"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.MIXED,
    stageDependency: "stage_4_profile_foundation",
    completionWeight: 2,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.PORTFOLIO,
    order: 21,
    section: PROFILE_SECTION_KEY.PROOF,
    title: "Portfolio",
    shortLabel: "Portfolio",
    description: "Reserve portfolio references for public credibility without implementing portfolio management now.",
    routeSegment: "portfolio",
    required: false,
    skippable: true,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.SERVICE_CATEGORIES],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.CASE_STUDIES],
    estimatedMinutes: 6,
    fields: ["proof.portfolioItems"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PUBLIC,
    futureFeature: "portfolio_manager",
    stageDependency: "future_portfolio_stage",
    completionWeight: 3,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.CASE_STUDIES,
    order: 22,
    section: PROFILE_SECTION_KEY.PROOF,
    title: "Case Studies",
    shortLabel: "Cases",
    description: "Prepare case study references for future proof-backed profile credibility.",
    routeSegment: "case-studies",
    required: false,
    skippable: true,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.PORTFOLIO],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.PROOF_VAULT],
    estimatedMinutes: 8,
    fields: ["proof.caseStudies"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PUBLIC,
    futureFeature: "case_study_manager",
    stageDependency: "future_case_study_stage",
    completionWeight: 3,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.PROOF_VAULT,
    order: 23,
    section: PROFILE_SECTION_KEY.PROOF,
    title: "Proof Vault",
    shortLabel: "Proof",
    description: "Reserve proof vault references without implementing proof upload or extraction in this prompt.",
    routeSegment: "proof-vault",
    required: false,
    skippable: true,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.CASE_STUDIES],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.CERTIFICATIONS],
    estimatedMinutes: 5,
    fields: ["proof.proofAssetRefs", "proof.publicProofHighlights"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.MIXED,
    futureFeature: "proof_vault_connection",
    stageDependency: "stage_23_proof_vault",
    completionWeight: 3,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.CERTIFICATIONS,
    order: 24,
    section: PROFILE_SECTION_KEY.PROOF,
    title: "Certifications",
    shortLabel: "Certs",
    description: "Capture public certification references for future trust and matching signals.",
    routeSegment: "certifications",
    required: false,
    skippable: true,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.PROOF_VAULT],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.ACHIEVEMENTS],
    estimatedMinutes: 4,
    fields: ["proof.certifications"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PUBLIC,
    stageDependency: "stage_4_profile_foundation",
    completionWeight: 2,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.ACHIEVEMENTS,
    order: 25,
    section: PROFILE_SECTION_KEY.PROOF,
    title: "Achievements",
    shortLabel: "Wins",
    description: "Capture public achievements that may later support reputation and discovery.",
    routeSegment: "achievements",
    required: false,
    skippable: true,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.CERTIFICATIONS],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.AVAILABILITY],
    estimatedMinutes: 4,
    fields: ["proof.achievements"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PUBLIC,
    stageDependency: "stage_4_profile_foundation",
    completionWeight: 2,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.AVAILABILITY,
    order: 26,
    section: PROFILE_SECTION_KEY.BUSINESS_READINESS,
    title: "Availability",
    shortLabel: "Available",
    description: "Capture provider availability status for future discovery and matching.",
    routeSegment: "availability",
    required: true,
    skippable: false,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.SERVICE_CATEGORIES],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.CAPACITY],
    estimatedMinutes: 3,
    fields: ["businessReadiness.availability", "professionalIdentity.availabilityStatus"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PUBLIC,
    stageDependency: "stage_4_profile_foundation",
    completionWeight: 3,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.CAPACITY,
    order: 27,
    section: PROFILE_SECTION_KEY.BUSINESS_READINESS,
    title: "Capacity",
    shortLabel: "Capacity",
    description: "Capture workload capacity to avoid poor matches and future delivery risk.",
    routeSegment: "capacity",
    required: false,
    skippable: true,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.AVAILABILITY],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.PAYMENT_METHODS],
    estimatedMinutes: 3,
    fields: ["businessReadiness.capacity"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.MIXED,
    stageDependency: "stage_4_profile_foundation",
    completionWeight: 2,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.PAYMENT_METHODS,
    order: 28,
    section: PROFILE_SECTION_KEY.BUSINESS_READINESS,
    title: "Payment Methods",
    shortLabel: "Payments",
    description: "Reserve private payment readiness fields for future payment integration without collecting payment data now.",
    routeSegment: "payment-methods",
    required: false,
    skippable: true,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.CAPACITY],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.TAX_INFORMATION],
    estimatedMinutes: 4,
    fields: ["businessReadiness.paymentMethods"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PRIVATE,
    futureFeature: "payments_profile_readiness",
    stageDependency: "future_payments_stage",
    completionWeight: 1,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.TAX_INFORMATION,
    order: 29,
    section: PROFILE_SECTION_KEY.BUSINESS_READINESS,
    title: "Tax Information",
    shortLabel: "Tax",
    description: "Reserve private tax readiness status for future payments and compliance workflows.",
    routeSegment: "tax-information",
    required: false,
    skippable: true,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.PAYMENT_METHODS],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.INVOICE_SETTINGS],
    estimatedMinutes: 4,
    fields: ["businessReadiness.taxReadiness"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PRIVATE,
    futureFeature: "tax_readiness_workflow",
    stageDependency: "future_payments_stage",
    completionWeight: 1,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.INVOICE_SETTINGS,
    order: 30,
    section: PROFILE_SECTION_KEY.BUSINESS_READINESS,
    title: "Invoice Settings",
    shortLabel: "Invoices",
    description: "Reserve private invoice preference structure for future billing workflows.",
    routeSegment: "invoice-settings",
    required: false,
    skippable: true,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.TAX_INFORMATION],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.EMAIL_VERIFICATION],
    estimatedMinutes: 4,
    fields: ["businessReadiness.invoiceSettings"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PRIVATE,
    futureFeature: "invoice_settings",
    stageDependency: "future_payments_stage",
    completionWeight: 1,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.EMAIL_VERIFICATION,
    order: 31,
    section: PROFILE_SECTION_KEY.TRUST_VERIFICATION,
    title: "Email Verification",
    shortLabel: "Email",
    description: "Track email verification readiness from the existing auth system without creating new verification logic.",
    routeSegment: "email-verification",
    required: true,
    skippable: false,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.CONTACT_INFORMATION],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.PHONE_VERIFICATION],
    estimatedMinutes: 2,
    fields: ["trustVerification.emailVerification"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PRIVATE,
    stageDependency: "stage_2_auth_verification",
    completionWeight: 3,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.PHONE_VERIFICATION,
    order: 32,
    section: PROFILE_SECTION_KEY.TRUST_VERIFICATION,
    title: "Phone Verification",
    shortLabel: "Phone",
    description: "Reserve phone verification status for future trust workflows.",
    routeSegment: "phone-verification",
    required: false,
    skippable: true,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.EMAIL_VERIFICATION],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.ID_VERIFICATION],
    estimatedMinutes: 3,
    fields: ["trustVerification.phoneVerification"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PRIVATE,
    futureFeature: "phone_verification",
    stageDependency: "future_verification_stage",
    completionWeight: 1,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.ID_VERIFICATION,
    order: 33,
    section: PROFILE_SECTION_KEY.TRUST_VERIFICATION,
    title: "ID Verification",
    shortLabel: "ID",
    description: "Reserve identity verification state without granting identity verification claims.",
    routeSegment: "id-verification",
    required: false,
    skippable: true,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.PHONE_VERIFICATION],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.BUSINESS_VERIFICATION],
    estimatedMinutes: 5,
    fields: ["trustVerification.idVerification"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PRIVATE,
    futureFeature: "identity_verification",
    stageDependency: "future_verification_stage",
    completionWeight: 2,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.BUSINESS_VERIFICATION,
    order: 34,
    section: PROFILE_SECTION_KEY.TRUST_VERIFICATION,
    title: "Business Verification",
    shortLabel: "Business",
    description: "Reserve business verification state for agencies and organizations.",
    routeSegment: "business-verification",
    required: false,
    skippable: true,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.ID_VERIFICATION],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.SOCIAL_VERIFICATION],
    estimatedMinutes: 5,
    fields: ["trustVerification.businessVerification"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PRIVATE,
    futureFeature: "business_verification",
    stageDependency: "future_verification_stage",
    completionWeight: 2,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.SOCIAL_VERIFICATION,
    order: 35,
    section: PROFILE_SECTION_KEY.TRUST_VERIFICATION,
    title: "Social Verification",
    shortLabel: "Social",
    description: "Reserve social verification state for future trust and identity workflows.",
    routeSegment: "social-verification",
    required: false,
    skippable: true,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.BUSINESS_VERIFICATION],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.PREFERRED_INDUSTRIES],
    estimatedMinutes: 4,
    fields: ["trustVerification.socialVerification", "trustVerification.verificationBadge"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.MIXED,
    futureFeature: "social_verification",
    stageDependency: "future_verification_stage",
    completionWeight: 2,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.PREFERRED_INDUSTRIES,
    order: 36,
    section: PROFILE_SECTION_KEY.GROWTH_INTELLIGENCE,
    title: "Preferred Industries",
    shortLabel: "Industries",
    description: "Capture private matching preferences for industries the provider wants to serve.",
    routeSegment: "preferred-industries",
    required: false,
    skippable: true,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.INDUSTRY],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.PREFERRED_BUDGET_RANGE],
    estimatedMinutes: 4,
    fields: ["matchingPreferences.preferredIndustries"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PRIVATE,
    stageDependency: "future_matching_stage",
    completionWeight: 2,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.PREFERRED_BUDGET_RANGE,
    order: 37,
    section: PROFILE_SECTION_KEY.GROWTH_INTELLIGENCE,
    title: "Preferred Budget Range",
    shortLabel: "Budget",
    description: "Capture private budget preferences for future matching and opportunity quality.",
    routeSegment: "preferred-budget-range",
    required: false,
    skippable: true,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.PREFERRED_INDUSTRIES],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.PREFERRED_CLIENT_TYPE],
    estimatedMinutes: 3,
    fields: ["matchingPreferences.preferredBudgets", "businessReadiness.preferredBudgetRange"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PRIVATE,
    stageDependency: "future_matching_stage",
    completionWeight: 2,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.PREFERRED_CLIENT_TYPE,
    order: 38,
    section: PROFILE_SECTION_KEY.GROWTH_INTELLIGENCE,
    title: "Preferred Client Type",
    shortLabel: "Client Type",
    description: "Capture private client-type preferences for future matching quality.",
    routeSegment: "preferred-client-type",
    required: false,
    skippable: true,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.PREFERRED_BUDGET_RANGE],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.PREFERRED_PROJECT_LENGTH],
    estimatedMinutes: 3,
    fields: ["matchingPreferences.preferredClientTypes", "businessReadiness.preferredClientType"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PRIVATE,
    stageDependency: "future_matching_stage",
    completionWeight: 2,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.PREFERRED_PROJECT_LENGTH,
    order: 39,
    section: PROFILE_SECTION_KEY.GROWTH_INTELLIGENCE,
    title: "Preferred Project Length",
    shortLabel: "Length",
    description: "Capture private project-length preferences for future matching and capacity planning.",
    routeSegment: "preferred-project-length",
    required: false,
    skippable: true,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.PREFERRED_CLIENT_TYPE],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.MATCHING_PREFERENCES],
    estimatedMinutes: 3,
    fields: ["matchingPreferences.preferredProjectLengths", "businessReadiness.preferredProjectLength"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PRIVATE,
    stageDependency: "future_matching_stage",
    completionWeight: 2,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.MATCHING_PREFERENCES,
    order: 40,
    section: PROFILE_SECTION_KEY.GROWTH_INTELLIGENCE,
    title: "Matching Preferences",
    shortLabel: "Matching",
    description: "Capture preferred challenge types, excluded categories, timezone preference, and response preference.",
    routeSegment: "matching-preferences",
    required: false,
    skippable: true,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.PREFERRED_PROJECT_LENGTH],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.AI_PROFILE_AUDIT],
    estimatedMinutes: 5,
    fields: ["matchingPreferences.preferredChallengeTypes", "matchingPreferences.excludedCategories", "matchingPreferences.timezonePreference", "matchingPreferences.responsePreference"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.PRIVATE,
    stageDependency: "future_matching_stage",
    completionWeight: 2,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.AI_PROFILE_AUDIT,
    order: 41,
    section: PROFILE_SECTION_KEY.GROWTH_INTELLIGENCE,
    title: "AI Profile Audit",
    shortLabel: "AI Audit",
    description: "Reserve AI audit state without calling AI services or creating audit results.",
    routeSegment: "ai-profile-audit",
    required: false,
    skippable: true,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.BIO, PROFILE_ONBOARDING_STEP_IDS.SKILLS],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.MISSING_REQUIREMENTS_CHECK],
    estimatedMinutes: 2,
    fields: ["growthIntelligence.aiProfileAuditStatus", "growthIntelligence.lastAuditAt"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.INTERNAL,
    futureFeature: "ai_profile_audit",
    stageDependency: "future_ai_stage",
    completionWeight: 1,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.MISSING_REQUIREMENTS_CHECK,
    order: 42,
    section: PROFILE_SECTION_KEY.GROWTH_INTELLIGENCE,
    title: "Missing Requirements Check",
    shortLabel: "Checklist",
    description: "Reserve readiness checklist structure for future publish blocking and recommendations.",
    routeSegment: "missing-requirements-check",
    required: true,
    skippable: false,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.AI_PROFILE_AUDIT],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.PROFILE_STRENGTH_SCORE],
    estimatedMinutes: 2,
    fields: ["growthIntelligence.missingRequirements", "growthIntelligence.readinessChecklist"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.INTERNAL,
    stageDependency: "stage_4_profile_foundation",
    completionWeight: 2,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.PROFILE_STRENGTH_SCORE,
    order: 43,
    section: PROFILE_SECTION_KEY.GROWTH_INTELLIGENCE,
    title: "Profile Strength Score",
    shortLabel: "Strength",
    description: "Reserve profile strength score state without calculating or displaying fake score values.",
    routeSegment: "profile-strength-score",
    required: false,
    skippable: true,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.MISSING_REQUIREMENTS_CHECK],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.TRUST_READINESS_SCORE],
    estimatedMinutes: 1,
    fields: ["trustVerification.profileStrengthScore", "onboarding.profileStrength"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.INTERNAL,
    futureFeature: "profile_strength_engine",
    stageDependency: "future_scoring_stage",
    completionWeight: 1,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.TRUST_READINESS_SCORE,
    order: 44,
    section: PROFILE_SECTION_KEY.GROWTH_INTELLIGENCE,
    title: "Trust Readiness Score",
    shortLabel: "Trust",
    description: "Reserve trust readiness score state without creating fake trust or proof claims.",
    routeSegment: "trust-readiness-score",
    required: false,
    skippable: true,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.PROFILE_STRENGTH_SCORE],
    unlocks: [PROFILE_ONBOARDING_STEP_IDS.PUBLISH_PROFILE],
    estimatedMinutes: 1,
    fields: ["trustVerification.trustReadinessScore", "onboarding.trustReadiness"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.INTERNAL,
    futureFeature: "trust_readiness_engine",
    stageDependency: "future_trust_stage",
    completionWeight: 1,
  }),
  step({
    id: PROFILE_ONBOARDING_STEP_IDS.PUBLISH_PROFILE,
    order: 45,
    section: PROFILE_SECTION_KEY.REVIEW_PUBLISH,
    title: "Publish Profile",
    shortLabel: "Publish",
    description: "Prepare the final review and publish gate for public-safe profile data.",
    routeSegment: "publish-profile",
    required: true,
    skippable: false,
    dependsOn: [PROFILE_ONBOARDING_STEP_IDS.MISSING_REQUIREMENTS_CHECK],
    estimatedMinutes: 5,
    fields: ["status", "visibility", "publishedAt"],
    privacyLevel: PROFILE_PRIVACY_LEVEL.MIXED,
    stageDependency: "future_publish_workflow",
    completionWeight: 4,
  }),
]);

export const PROFILE_ONBOARDING_STEP_MAP = Object.freeze(
  PROFILE_ONBOARDING_STEPS.reduce((registry, onboardingStep) => {
    registry[onboardingStep.id] = onboardingStep;
    return registry;
  }, {}),
);

export const PROFILE_ONBOARDING_STEP_ORDER = Object.freeze(
  PROFILE_ONBOARDING_STEPS.map((onboardingStep) => onboardingStep.id),
);
