// @ts-check

import { PROFILE_SECTION_KEY } from "../../types/profile.js";

export const PROFILE_ONBOARDING_STEP_IDS = Object.freeze({
  ACCOUNT_TYPE: "accountType",
  ACHIEVEMENTS: "achievements",
  AI_PROFILE_AUDIT: "aiProfileAudit",
  AVAILABILITY: "availability",
  BIO: "bio",
  BUSINESS_VERIFICATION: "businessVerification",
  CAPACITY: "capacity",
  CASE_STUDIES: "caseStudies",
  CERTIFICATIONS: "certifications",
  CONTACT_INFORMATION: "contactInformation",
  COVER_BANNER: "coverBanner",
  DELIVERY_TIMELINES: "deliveryTimelines",
  EMAIL_VERIFICATION: "emailVerification",
  EXPERIENCE_LEVELS: "experienceLevels",
  ID_VERIFICATION: "idVerification",
  INDUSTRY: "industry",
  INVOICE_SETTINGS: "invoiceSettings",
  MATCHING_PREFERENCES: "matchingPreferences",
  MISSING_REQUIREMENTS_CHECK: "missingRequirementsCheck",
  NICHE: "niche",
  OUTCOME_OFFERS: "outcomeOffers",
  PAYMENT_METHODS: "paymentMethods",
  PERSONAL_INFORMATION: "personalInformation",
  PHONE_VERIFICATION: "phoneVerification",
  PLATFORMS: "platforms",
  PORTFOLIO: "portfolio",
  PREFERRED_BUDGET_RANGE: "preferredBudgetRange",
  PREFERRED_CLIENT_TYPE: "preferredClientType",
  PREFERRED_INDUSTRIES: "preferredIndustries",
  PREFERRED_PROJECT_LENGTH: "preferredProjectLength",
  PRICING_MODELS: "pricingModels",
  PROFESSIONAL_HEADLINE: "professionalHeadline",
  PROFILE_PHOTO: "profilePhoto",
  PROFILE_STRENGTH_SCORE: "profileStrengthScore",
  PROOF_VAULT: "proofVault",
  PUBLISH_PROFILE: "publishProfile",
  REVISION_POLICIES: "revisionPolicies",
  SERVICE_CATEGORIES: "serviceCategories",
  SKILL_VERIFICATION: "skillVerification",
  SKILLS: "skills",
  SOCIAL_VERIFICATION: "socialVerification",
  TARGET_CLIENT: "targetClient",
  TAX_INFORMATION: "taxInformation",
  TOOLS: "tools",
  TRUST_READINESS_SCORE: "trustReadinessScore",
});

/** @type {readonly import("../../types/profile.js").ProfileSectionConfig[]} */
export const PROFILE_SECTIONS = Object.freeze([
  Object.freeze({
    key: PROFILE_SECTION_KEY.IDENTITY,
    label: "Identity",
    description: "Account type, personal information, profile media, and contact readiness.",
    order: 1,
    requiredForPublish: true,
    steps: Object.freeze([
      PROFILE_ONBOARDING_STEP_IDS.ACCOUNT_TYPE,
      PROFILE_ONBOARDING_STEP_IDS.PERSONAL_INFORMATION,
      PROFILE_ONBOARDING_STEP_IDS.PROFILE_PHOTO,
      PROFILE_ONBOARDING_STEP_IDS.COVER_BANNER,
      PROFILE_ONBOARDING_STEP_IDS.CONTACT_INFORMATION,
    ]),
    completionWeight: 12,
    publicImpact: "high",
    trustImpact: "medium",
    matchingImpact: "low",
  }),
  Object.freeze({
    key: PROFILE_SECTION_KEY.PROFESSIONAL_IDENTITY,
    label: "Professional Identity",
    description: "Headline, bio, industry focus, niche, and target client positioning.",
    order: 2,
    requiredForPublish: true,
    steps: Object.freeze([
      PROFILE_ONBOARDING_STEP_IDS.PROFESSIONAL_HEADLINE,
      PROFILE_ONBOARDING_STEP_IDS.BIO,
      PROFILE_ONBOARDING_STEP_IDS.INDUSTRY,
      PROFILE_ONBOARDING_STEP_IDS.NICHE,
      PROFILE_ONBOARDING_STEP_IDS.TARGET_CLIENT,
    ]),
    completionWeight: 14,
    publicImpact: "high",
    trustImpact: "medium",
    matchingImpact: "high",
  }),
  Object.freeze({
    key: PROFILE_SECTION_KEY.SKILLS,
    label: "Skills",
    description: "Skills, tools, platforms, experience levels, and future skill verification.",
    order: 3,
    requiredForPublish: true,
    steps: Object.freeze([
      PROFILE_ONBOARDING_STEP_IDS.SKILLS,
      PROFILE_ONBOARDING_STEP_IDS.TOOLS,
      PROFILE_ONBOARDING_STEP_IDS.PLATFORMS,
      PROFILE_ONBOARDING_STEP_IDS.EXPERIENCE_LEVELS,
      PROFILE_ONBOARDING_STEP_IDS.SKILL_VERIFICATION,
    ]),
    completionWeight: 12,
    publicImpact: "high",
    trustImpact: "medium",
    matchingImpact: "high",
  }),
  Object.freeze({
    key: PROFILE_SECTION_KEY.SERVICES,
    label: "Services",
    description: "Service categories, outcome offer connections, pricing models, timelines, and revision policy readiness.",
    order: 4,
    requiredForPublish: true,
    steps: Object.freeze([
      PROFILE_ONBOARDING_STEP_IDS.SERVICE_CATEGORIES,
      PROFILE_ONBOARDING_STEP_IDS.OUTCOME_OFFERS,
      PROFILE_ONBOARDING_STEP_IDS.PRICING_MODELS,
      PROFILE_ONBOARDING_STEP_IDS.DELIVERY_TIMELINES,
      PROFILE_ONBOARDING_STEP_IDS.REVISION_POLICIES,
    ]),
    completionWeight: 12,
    publicImpact: "high",
    trustImpact: "low",
    matchingImpact: "high",
  }),
  Object.freeze({
    key: PROFILE_SECTION_KEY.PROOF,
    label: "Proof",
    description: "Portfolio, case studies, proof vault connections, certifications, and achievements.",
    order: 5,
    requiredForPublish: false,
    steps: Object.freeze([
      PROFILE_ONBOARDING_STEP_IDS.PORTFOLIO,
      PROFILE_ONBOARDING_STEP_IDS.CASE_STUDIES,
      PROFILE_ONBOARDING_STEP_IDS.PROOF_VAULT,
      PROFILE_ONBOARDING_STEP_IDS.CERTIFICATIONS,
      PROFILE_ONBOARDING_STEP_IDS.ACHIEVEMENTS,
    ]),
    completionWeight: 14,
    publicImpact: "high",
    trustImpact: "high",
    matchingImpact: "medium",
  }),
  Object.freeze({
    key: PROFILE_SECTION_KEY.BUSINESS_READINESS,
    label: "Business Readiness",
    description: "Availability, capacity, payment readiness, tax readiness, and invoice settings.",
    order: 6,
    requiredForPublish: false,
    steps: Object.freeze([
      PROFILE_ONBOARDING_STEP_IDS.AVAILABILITY,
      PROFILE_ONBOARDING_STEP_IDS.CAPACITY,
      PROFILE_ONBOARDING_STEP_IDS.PAYMENT_METHODS,
      PROFILE_ONBOARDING_STEP_IDS.TAX_INFORMATION,
      PROFILE_ONBOARDING_STEP_IDS.INVOICE_SETTINGS,
    ]),
    completionWeight: 10,
    publicImpact: "medium",
    trustImpact: "medium",
    matchingImpact: "high",
  }),
  Object.freeze({
    key: PROFILE_SECTION_KEY.TRUST_VERIFICATION,
    label: "Trust & Verification",
    description: "Email, phone, identity, business, and social verification readiness.",
    order: 7,
    requiredForPublish: false,
    steps: Object.freeze([
      PROFILE_ONBOARDING_STEP_IDS.EMAIL_VERIFICATION,
      PROFILE_ONBOARDING_STEP_IDS.PHONE_VERIFICATION,
      PROFILE_ONBOARDING_STEP_IDS.ID_VERIFICATION,
      PROFILE_ONBOARDING_STEP_IDS.BUSINESS_VERIFICATION,
      PROFILE_ONBOARDING_STEP_IDS.SOCIAL_VERIFICATION,
    ]),
    completionWeight: 10,
    publicImpact: "medium",
    trustImpact: "high",
    matchingImpact: "medium",
  }),
  Object.freeze({
    key: PROFILE_SECTION_KEY.GROWTH_INTELLIGENCE,
    label: "Growth Intelligence",
    description: "Matching preferences, AI profile audit placeholders, missing requirement checks, and readiness scoring placeholders.",
    order: 8,
    requiredForPublish: false,
    steps: Object.freeze([
      PROFILE_ONBOARDING_STEP_IDS.PREFERRED_INDUSTRIES,
      PROFILE_ONBOARDING_STEP_IDS.PREFERRED_BUDGET_RANGE,
      PROFILE_ONBOARDING_STEP_IDS.PREFERRED_CLIENT_TYPE,
      PROFILE_ONBOARDING_STEP_IDS.PREFERRED_PROJECT_LENGTH,
      PROFILE_ONBOARDING_STEP_IDS.MATCHING_PREFERENCES,
      PROFILE_ONBOARDING_STEP_IDS.AI_PROFILE_AUDIT,
      PROFILE_ONBOARDING_STEP_IDS.MISSING_REQUIREMENTS_CHECK,
      PROFILE_ONBOARDING_STEP_IDS.PROFILE_STRENGTH_SCORE,
      PROFILE_ONBOARDING_STEP_IDS.TRUST_READINESS_SCORE,
    ]),
    completionWeight: 12,
    publicImpact: "low",
    trustImpact: "medium",
    matchingImpact: "high",
  }),
  Object.freeze({
    key: PROFILE_SECTION_KEY.REVIEW_PUBLISH,
    label: "Final Review & Publish",
    description: "Review public-safe profile data and publish when readiness gates pass.",
    order: 9,
    requiredForPublish: true,
    steps: Object.freeze([
      PROFILE_ONBOARDING_STEP_IDS.PUBLISH_PROFILE,
    ]),
    completionWeight: 4,
    publicImpact: "high",
    trustImpact: "medium",
    matchingImpact: "medium",
  }),
]);

export const PROFILE_SECTION_MAP = Object.freeze(
  PROFILE_SECTIONS.reduce((registry, section) => {
    registry[section.key] = section;
    return registry;
  }, {}),
);

export const PROFILE_SECTION_KEYS = Object.freeze(PROFILE_SECTIONS.map((section) => section.key));
