export const ERROR_CODES = Object.freeze({
  BAD_REQUEST: "BAD_REQUEST",
  CONFLICT: "CONFLICT",
  DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  FORBIDDEN: "FORBIDDEN",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INVALID_ID: "INVALID_ID",
  INVALID_JSON: "INVALID_JSON",
  INVALID_TOKEN: "INVALID_TOKEN",
  NOT_FOUND: "NOT_FOUND",
  RATE_LIMITED: "RATE_LIMITED",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  UNAUTHORIZED: "UNAUTHORIZED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
});

export function getDefaultErrorCode(statusCode = 500) {
  const codeByStatus = {
    400: ERROR_CODES.BAD_REQUEST,
    401: ERROR_CODES.UNAUTHORIZED,
    403: ERROR_CODES.FORBIDDEN,
    404: ERROR_CODES.NOT_FOUND,
    409: ERROR_CODES.CONFLICT,
    413: ERROR_CODES.FILE_TOO_LARGE,
    429: ERROR_CODES.RATE_LIMITED,
    503: ERROR_CODES.SERVICE_UNAVAILABLE,
  };

  return codeByStatus[statusCode] ?? ERROR_CODES.INTERNAL_ERROR;
}

